### ISSUE TITLE
features are not visible when text-field contains more then 255 characters

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis2web/qgis2web#947]
Using qgis 3.16.4 and q2w 3.16 I noticed not all features are visible on the preview map. The missing features are also not exported.

I happened to spot  a significant distinction between the features shown and not shown. The ones not shown have more than 256 characters in a textfield.
All features have information in that textfield, some longer sentences than others. The ones having more than 255 characters are not shown nor exported. I have tested this: 255 is shown, 256 is not.

Is there a setting anywhere that I could change so these features are shown?

**Comment by Jeroen-GroeneBij** [comment]
Hi ,

Just a quick update. The bug seems to be part of the creation proces. After replacing the long text-entries with short placeholders I could export the map. I edited the .js file in the data folder replacing the spaceholder text with the original text containing over 256 characters and the updated map still works. So, it seems it is not a Leaflet issue, but something within the proces of creating the preview / actual map within q2w.

**Comment by boesiii** [comment]
What is the data source?  Shapefiles?

**Comment by Jeroen-GroeneBij** [comment]
Data source is csv joined with a vectorlayer. Both csv and vectorlayer are stored in postgis. Join is made with dbmanager.

**Comment by tomchadwin** [comment]
Can you try without a join? I never know how well supported they are.

**Comment by Jeroen-GroeneBij** [comment]
Hi Tom,

here is a gpkg I created. The features in the top right have a value of exactly 256 characters (11 features) in the field named "vrij".
You can select them using select by expression: field vrij = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa256

When you export this map, it will not show those 11 features.

[test256char.zip](https://github.com/tomchadwin/qgis2web/files/6165781/test256char.zip)

**Comment by patml1** [comment]
I have this problem too. I have reproduced it in a single layer with a single text field in a spatialite table, in a memory-only scratch later, and in a CSV file. A shapefile does not allow more than 256 characters in a text field anyway, so truncates it, but does at least export it OK. The problem occurs for Leaflet, Open Layers and Mapbox output options. The Mapbox GL JS option does not render the preview and stays as a 'waiting' cursor until I close QGIS.
This is otherwise a really brilliant plugin and is going to be useful for me. Thanks for creating it.

**Comment by MFFDM** [comment]
I have same problem too with CSV and GPKG :/

**Comment by Markeol** [comment]
Still same problem here with a gpkg file. I managed (few month ago) to export a map with an old version of qgis2web but since the last update can no longer do it?
 I need a solution, someone to an idea ?

**Comment by boesiii** [comment]
Can you include a sample of your data so we can test?

**Comment by Markeol** [comment]
Hi, 
Here there are some map points with long text attached.
When I want export this points with Qgis2web, only few points appears (those one with short text).

[TEST_MAP_TEXT.zip](https://github.com/tomchadwin/qgis2web/files/8649628/TEST_MAP_TEXT.zip)

**Comment by MFFDM** [comment]
> Still same problem here with a gpkg file. I managed (few month ago) to export a map with an old version of qgis2web but since the last update can no longer do it? I need a solution, someone to an idea ?

I did following:
1 - Export the layer to SHP. Automatically, this will  cut off fields longer than 255 characters.
2 - Create the mapweb with qgis2web.
3 - Edit the js file with the data to manually add the rest of the text.

As you can see, it is a slow process...

**Comment by Jeroen-GroeneBij** [comment]
Hi,

Is there any progress on this issue? Can I do something to help, like testing?
My experience with this issue is that:
it does not seem to be a leaflet issue, because the feature is rendered when the data .js file is edited after exporting.
it does not seem to be an data origin issue because this appears in all sorts of source data (postgis, gpkg, scratch layer, all with or without a csv join).
So probably there is a conversion step somewhere in the qgis2web code that has a 256 character limit...

**Comment by Markeol** [comment]
hi, yes i found a perfect solution. I just did a normal leaflet export. Then, I exported my database in geojson version. finally I replaced the file "nameofmybase.js" from the file data by my export in .geojson file (that i renamed in .js file). With notepad i edited the first lines of the new .jd file. And all works again !

**Comment by Michael-Z-Freeman** [comment]
Fix seems to work :)

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.

**Comment by ffierm** [comment]
Good morning Dears,

even though I'm using the latest versions (QGIS LTR + updated qgis2web), the problem is still present. The data source is geopackage, and the maximum number of (linear) features present is a few hundred...

Is there anyone who can help to solve this?

Best Regards,
Francesco

**Comment by andreaordonselli** [comment]
Please test this version, if the problem is solved I make a commit, Thanks

[qgis2web.zip](https://github.com/user-attachments/files/30323552/qgis2web.zip)

**Comment by ffierm** [comment]
Hi Andrea, I've' tested the **ZIP** into **QGIS 3.44.12-1** and **QGIS 4.2.0-1**.

The issue has been solved!

Thank you so much...

**Comment by andreaordonselli** [comment]
In version [4.3.2](https://plugins.qgis.org/plugins/qgis2web/version/4.3.2/) the issue discussed in this thread is resolved. The update will soon be available in the QGIS plugin repository.

I would greatly appreciate it if you would consider donating a single or monthly virtual coffee through the button on the homepage to support the development of qgis2web.

Thank you for using the plugin.

Best regards.
